respawn:
  minutes_per_diamond: 5
  max_duration: 120
  enabled: true

chat:
  blocked-patterns:
    - '(?i)\b(n+[i1!]+gg+[e3]+r+|f+[a4]+g+|r+[e3]+t+[a4]+r+d+|d[i1]ck|h[o0]rny|p[o0]rn|[s$][e3]x|[s$]h[i1][t+][s$]?|[s$][l1]u[t+][s$]?)\b'
    - '(?i)\b(p+[e3]+n+[i1]+s+[e3]?|c[l1][i1][t+])\b'
    - '(?i)\b(n+[i1!]+q+q+[e3]+|t[a4]+p[e3]+t[a4]+r+[e3]+|p[e3]+d+[o0]+)\b'
    - '(?i)\b(g+[u]+[e3]+u+l+[e3]+|m+[e3]+r+d+[e3]+|b+[i1]+t+[e3]+|s+[u]+c+[e3]+[u]+r+|b+[o0]+u+g+n+[o0]+u+l+|p+[u]+t+[e3]+|p+[u]+t+[a4]+[s$]+[s$]*)\b'

worlds:
  end:
    enabled: true

border:
  expansion-items:
    DIAMOND: 10.0
    NETHERITE_INGOT: 45.0
    EMERALD: 5.0
    DRAGON_EGG: 5000.0
    NETHER_STAR: 300.0
    BEACON: 80.0