name: VachagerSMP
version: '1.0'
main: com.meekdev.vachager.VachagerSMP
api-version: '1.21'
authors: [Meek]
softdepend: [CarbonChat]
description: SMP
commands:
  chairs:
    description: Toggle the chair system
    usage: /<command>
    permission: vachager.chairs.toggle
  toggleend:
    description: Toggle the end dimension
    usage: /<command>
    permission: vachager.end.toggle


permissions:
  vachager.end.toggle:
    description: Allows toggling The End dimension
    default: op
  vachager.spawn.set:
    description: Allows setting spawn points
    default: true
  vachager.end.bypass:
    description: Allows bypassing End restrictions
    default: op